--Revenue generated by states with product Category

WITH customer_orders AS (
    SELECT 
        State, Category,
        Amount, Quantity  
	FROM Orders
	JOIN Details 
	ON orders.Order_ID = Details.Order_ID
)
SELECT 
    State, Category, 
    SUM(Quantity) * SUM(Amount) as Sum_revenue_generated
FROM customer_orders
GROUP BY State, Category
ORDER BY State, Sum_revenue_generated desc;