-- Revenue generated by products sub_category

WITH customer_orders AS (
    SELECT 
        Sub_Category, Amount, Quantity 
	FROM Orders
	JOIN Details 
	ON orders.Order_ID = Details.Order_ID
)
SELECT 
    Sub_Category,
    SUM(Quantity) * SUM(Amount) as total_revenue_generated
FROM customer_orders
GROUP BY Sub_Category
ORDER BY total_revenue_generated desc


--Revenue generated by products category

 WITH customer_orders AS (
    SELECT 
        Order_ID, Order_Date, Customer_Name,
        State, City, Category, Sub_Category,
        Amount, Quantity, Payment Mode, Profit 
	FROM Orders
	JOIN Details 
	ON orders.Order_ID = Details.Order_ID
)
SELECT 
    Category,
    SUM(Quantity) *SUM("Amount") as total_revenue_generated
FROM customer_orders
GROUP BY Category
ORDER BY total_revenue_generated desc

