-- Revenue generated by products

with customer_orders as (select orders."Order_ID", orders."Order_Date", "CustomerName", orders."State", orders."City", "Category",
		"Sub-Category", "Amount", "Quantity", "Payment Mode", "Profit"
		from orders
		join  "Details" 
		on orders."Order_ID" = "Details"."Order_ID"
)
select "Sub-Category", sum("Quantity") * sum("Amount") as total_revenue_generated
from customer_orders
group by "Sub-Category"
order by total_revenue_generated desc