-- Revenue generated by products sub_category

WITH customer_orders as (
    SELECT 
        orders."Order_ID", orders."Order_Date",
        "CustomerName", orders."State", orders."City",
        "Category", "Sub-Category", "Amount",
        "Quantity", "Payment Mode", "Profit"
	FROM orders
	JOIN  "Details" 
	ON orders."Order_ID" = "Details"."Order_ID"
)
SELECT 
    "Sub-Category",
    SUM("Quantity") * SUM("Amount") as total_revenue_generated
FROM customer_orders
GROUP BY "Sub-Category"
ORDER BY total_revenue_generated desc


--Revenue generated by products category

WITH customer_orders as (
    SELECT 
        orders."Order_ID", orders."Order_Date",
        "CustomerName", orders."State", orders."City",
        "Category", "Sub-Category", "Amount",
        "Quantity", "Payment Mode", "Profit"
	FROM orders
	JOIN  "Details" 
	ON orders."Order_ID" = "Details"."Order_ID"
)
SELECT 
    "Category",
    SUM("Quantity") *SUM("Amount") as total_revenue_generated
FROM customer_orders
GROUP BY "Category"
ORDER BY total_revenue_generated desc

